name: Deploy

on:
  pull_request:
    branches: [main, develop]

# Vercel requires one project for each directory in a monorepo:
# https://vercel.com/blog/monorepos

jobs:
  backend:
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.backend_deploy.outputs.preview-url }}
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_BACKEND_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      ENV_FILE: ./backend/.env
    steps:
      - name: Check Variables
        uses: 0xJem/secret-gate-action@v1.1.1
        with:
          inputsToCheck: VERCEL_TOKEN,GITHUB_TOKEN,VERCEL_ORG_ID,VERCEL_BACKEND_PROJECT_ID,JWT_SECRET,DISCORD_BOT_TOKEN
          # ,DISCORD_SERVER_ID,DISCORD_ROLE_ID,HASURA_ENDPOINT,HASURA_ADMIN_SECRET,ALCHEMY_MAINNET_API_KEY,ALCHEMY_RINKEBY_API_KEY,COVALENTHQ_API_KEY,ETHERSCAN_API_KEY,MORALIS_API_KEY
          failOnMissing: true
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: "backend/.nvmrc"
      # Write variables that will be used by Vercel during deployment
      - name: Write environment
        run: |
          touch ${{ env.ENV_FILE }}
          echo JWT_SECRET=${{ env.JWT_SECRET }} >> ${{ env.ENV_FILE }}
          echo DISCORD_BOT_TOKEN=${{ env.DISCORD_BOT_TOKEN }} >> ${{ env.ENV_FILE }}
      - uses: amondnet/vercel-action@v20
        id: backend_deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
          working-directory: ./backend
  frontend:
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.frontend_deploy.outputs.preview-url }}
    needs: backend
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_FRONTEND_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
      NEXT_PUBLIC_BACKEND_API_URL: ${{ needs.backend.outputs.preview-url }}
      ENV_FILE: ./frontend/.env
    steps:
      - name: Check Variables
        uses: 0xJem/secret-gate-action@v1.1.1
        with:
          inputsToCheck: VERCEL_TOKEN,GITHUB_TOKEN,VERCEL_ORG_ID,VERCEL_FRONTEND_PROJECT_ID,NEXT_PUBLIC_BACKEND_API_URL
          failOnMissing: true
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: "frontend/.nvmrc"
      # Write variables that will be used by Vercel during deployment
      - name: Write environment
        run: |
          touch ${{ env.ENV_FILE }}
          echo NEXT_PUBLIC_BACKEND_API_URL=${{ env.NEXT_PUBLIC_BACKEND_API_URL }} >> ${{ env.ENV_FILE }}
      - uses: amondnet/vercel-action@v20
        id: frontend_deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
          working-directory: ./frontend
  discord:
    runs-on: ubuntu-latest
    needs: frontend
    env:
      DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
      FRONTEND_URL: ${{ needs.frontend.outputs.preview-url }}
      VERCEL_DISCORD_PROJECT_ID: ${{ secrets.VERCEL_DISCORD_PROJECT_ID }}
      ENV_FILE: ./discord/.env
    steps:
      - name: Check Variables
        uses: 0xJem/secret-gate-action@v1.1.1
        with:
          inputsToCheck: DISCORD_APP_ID,DISCORD_BOT_TOKEN,DISCORD_PUBLIC_KEY,JWT_SECRET,JWT_EXPIRATION_TIME,FRONTEND_URL,VERCEL_DISCORD_PROJECT_ID
          failOnMissing: true
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: "discord/.nvmrc"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./discord
      - name: Sync Discord commands
        run: yarn run slash-up sync
        working-directory: ./discord
      # Write variables that will be used by Vercel during deployment
      # Vercel will return a non-zero error code when adding an existing environment variable, so we remove first
      # Vercel will return a non-zero error code when removing a non-existent environment variable, so we capture that
      - name: Write environment to Vercel
        run: |
          (vercel env rm JWT_SECRET || exit 0) && echo ${{ env.JWT_SECRET }} > ./discord/secret.txt && vercel env add JWT_SECRET preview < ./discord/secret.txt
          (vercel env rm JWT_EXPIRATION_TIME || exit 0) && echo ${{ env.JWT_EXPIRATION_TIME }} > ./discord/secret.txt && vercel env add JWT_EXPIRATION_TIME preview < ./discord/secret.txt
          (vercel env rm DISCORD_APP_ID || exit 0) && echo ${{ env.DISCORD_APP_ID }} > ./discord/secret.txt && vercel env add DISCORD_APP_ID preview < ./discord/secret.txt
          (vercel env rm DISCORD_BOT_TOKEN || exit 0) && echo ${{ env.DISCORD_BOT_TOKEN }} > ./discord/secret.txt && vercel env add DISCORD_BOT_TOKEN preview < ./discord/secret.txt
          (vercel env rm DISCORD_PUBLIC_KEY || exit 0) && echo ${{ env.DISCORD_PUBLIC_KEY }} > ./discord/secret.txt && vercel env add DISCORD_PUBLIC_KEY preview < ./discord/secret.txt
          (vercel env rm FRONTEND_URL || exit 0) && echo ${{ env.FRONTEND_URL }} > ./discord/secret.txt && vercel env add FRONTEND_URL preview < ./discord/secret.txt
      - uses: amondnet/vercel-action@v20
        id: discord_deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_DISCORD_PROJECT_ID }}
          working-directory: ./discord

  # TODO prod flag
  # TODO prod domain
  # TODO run tests
